### ISSUE TITLE
AttributeError: type object 'InterpType' has no attribute 'HYPER'

### ISSUE THREAD

**Issue by ridders** [ridders/osprai#11]
raceback (most recent call last):
  File "osprai.py", line 105, in import_prep_apply_clicked
    image_list = pool.map(partial_harvester, self.temp_index[:40])
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
AttributeError: type object 'InterpType' has no attribute 'HYPER'
C:\Users\Public\Pictures\Sample Pictures\Lighthouse.jpgC:\Users\Public\Pictures\Sample Pictures\Penguins.jpg

**Comment by ridders** [comment]
After changing interptype to bilinear the same error still occurs:

Traceback (most recent call last):
  File "osprai.py", line 104, in import_prep_apply_clicked
    image_list = pool.map(partial_harvester, self.temp_index[:40])
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
AttributeError: type object 'InterpType' has no attribute 'BILINEAR'

**Comment by ridders** [comment]
This appears to be resolved when ThreadPool is set to 1. Anything above this appears to cause errors.
